insert into ballparks (id, home_team_id, name, city, state) values (1, 1, 'Miboo', 'Concord', 'CA');
insert into ballparks (id, home_team_id, name, city, state) values (2, 2, 'Fiveclub', 'San Francisco', 'CA');
insert into ballparks (id, home_team_id, name, city, state) values (3, 3, 'Midel', 'Chattanooga', 'TN');
insert into ballparks (id, home_team_id, name, city, state) values (4, 4, 'Topicstorm', 'North Hollywood', 'CA');
insert into ballparks (id, home_team_id, name, city, state) values (5, 5, 'Babbleset', 'Washington', 'DC');
insert into ballparks (id, home_team_id, name, city, state) values (6, 6, 'Viva', 'Richmond', 'VA');
insert into ballparks (id, home_team_id, name, city, state) values (7, 7, 'Skalith', 'Alexandria', 'VA');
insert into ballparks (id, home_team_id, name, city, state) values (8, 8, 'Realblab', 'Des Moines', 'IA');
insert into ballparks (id, home_team_id, name, city, state) values (9, 9, 'Rhynyx', 'Austin', 'TX');
insert into ballparks (id, home_team_id, name, city, state) values (10, 10, 'Ailane', 'Long Beach', 'CA');
insert into ballparks (id, home_team_id, name, city, state) values (11, 11, 'Centizu', 'San Jose', 'CA');
insert into ballparks (id, home_team_id, name, city, state) values (12, 12, 'Topiclounge', 'Cleveland', 'OH');
insert into ballparks (id, home_team_id, name, city, state) values (13, 13, 'Quire', 'Springfield', 'IL');
insert into ballparks (id, home_team_id, name, city, state) values (14, 14, 'Izio', 'Chicago', 'IL');
insert into ballparks (id, home_team_id, name, city, state) values (15, 15, 'Camido', 'Hollywood', 'FL');
insert into ballparks (id, home_team_id, name, city, state) values (16, 16, 'Gigabox', 'Cincinnati', 'OH');
insert into ballparks (id, home_team_id, name, city, state) values (17, 17, 'Skiptube', 'Kansas City', 'MO');
insert into ballparks (id, home_team_id, name, city, state) values (18, 18, 'Babbleset', 'Atlanta', 'GA');
insert into ballparks (id, home_team_id, name, city, state) values (19, 19, 'Wikibox', 'Jackson', 'TN');
insert into ballparks (id, home_team_id, name, city, state) values (20, 20, 'Youbridge', 'Grand Rapids', 'MI');
insert into ballparks (id, home_team_id, name, city, state) values (21, 21, 'Jetpulse', 'Houston', 'TX');
insert into ballparks (id, home_team_id, name, city, state) values (22, 22, 'Babbleblab', 'Brooklyn', 'NY');
insert into ballparks (id, home_team_id, name, city, state) values (23, 23, 'Pixonyx', 'Daytona Beach', 'FL');
insert into ballparks (id, home_team_id, name, city, state) values (24, 24, 'Tazzy', 'Independence', 'MO');
insert into ballparks (id, home_team_id, name, city, state) values (25, 25, 'Linktype', 'Saint Petersburg', 'FL');
insert into ballparks (id, home_team_id, name, city, state) values (26, 26, 'Dynabox', 'Savannah', 'GA');
insert into ballparks (id, home_team_id, name, city, state) values (27, 27, 'Zoomcast', 'Macon', 'GA');
insert into ballparks (id, home_team_id, name, city, state) values (28, 28, 'Zoomdog', 'Colorado Springs', 'CO');
insert into ballparks (id, home_team_id, name, city, state) values (29, 29, 'Brainbox', 'El Paso', 'TX');
insert into ballparks (id, home_team_id, name, city, state) values (30, 30, 'Edgeclub', 'Baton Rouge', 'LA');
