insert into teams (id, name, league) values (1, 'Dragon, western bearded', 'American');
insert into teams (id, name, league) values (2, 'Stork, black-necked', 'National');
insert into teams (id, name, league) values (3, 'Guerza', 'American');
insert into teams (id, name, league) values (4, 'Water monitor', 'American');
insert into teams (id, name, league) values (5, 'Legaan, Monitor (unidentified)', 'American');
insert into teams (id, name, league) values (6, 'Eurasian beaver', 'National');
insert into teams (id, name, league) values (7, 'Little heron', 'National');
insert into teams (id, name, league) values (8, 'Curlew, black', 'American');
insert into teams (id, name, league) values (9, 'Tyrant flycatcher', 'National');
insert into teams (id, name, league) values (10, 'Bottle-nose dolphin', 'American');
insert into teams (id, name, league) values (11, 'Gelada baboon', 'National');
insert into teams (id, name, league) values (12, 'Lilac-breasted roller', 'National');
insert into teams (id, name, league) values (13, 'Numbat', 'American');
insert into teams (id, name, league) values (14, 'Black-tailed prairie dog', 'American');
insert into teams (id, name, league) values (15, 'Blue-breasted cordon bleu', 'National');
insert into teams (id, name, league) values (16, 'Bird, black-throated butcher', 'American');
insert into teams (id, name, league) values (17, 'Common zebra', 'National');
insert into teams (id, name, league) values (18, 'Moccasin, water', 'American');
insert into teams (id, name, league) values (19, 'Hawk, ferruginous', 'American');
insert into teams (id, name, league) values (20, 'Stork, painted', 'American');
insert into teams (id, name, league) values (21, 'Bustard, denham''s', 'National');
insert into teams (id, name, league) values (22, 'Blackbuck', 'National');
insert into teams (id, name, league) values (23, 'African ground squirrel (unidentified)', 'American');
insert into teams (id, name, league) values (24, 'Fox, asian red', 'National');
insert into teams (id, name, league) values (25, 'Small-clawed otter', 'American');
insert into teams (id, name, league) values (26, 'Pie, indian tree', 'American');
insert into teams (id, name, league) values (27, 'African polecat', 'National');
insert into teams (id, name, league) values (28, 'Pelican, eastern white', 'American');
insert into teams (id, name, league) values (29, 'Hudsonian godwit', 'National');
insert into teams (id, name, league) values (30, 'Common long-nosed armadillo', 'National');
